// Generated by CoffeeScript 1.6.3
(function() {
  var Errors, EventEmitter, Stats,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Errors = require('./Errors');

  EventEmitter = require('events').EventEmitter;

  Stats = (function(_super) {
    __extends(Stats, _super);

    Stats.prototype._path = null;

    Stats.prototype._isFile = false;

    Stats.prototype._isDirectory = false;

    Stats.prototype._isLink = false;

    Stats.prototype._isSymlink = false;

    Stats.prototype.dev = 0;

    Stats.prototype.ino = 0;

    Stats.prototype.mode = 438;

    Stats.prototype.nlink = 0;

    Stats.prototype.uid = 100;

    Stats.prototype.gid = 100;

    Stats.prototype.rdev = 0;

    Stats.prototype.size = 0;

    Stats.prototype.blksize = 0;

    Stats.prototype.blocks = 1;

    Stats.prototype.atime = null;

    Stats.prototype.mtime = null;

    Stats.prototype.ctime = null;

    function Stats(_path, data) {
      var name, value;
      this._path = _path;
      if (data == null) {
        data = {};
      }
      this.atime = new Date;
      this.mtime = new Date;
      this.ctime = new Date;
      for (name in data) {
        value = data[name];
        if (typeof this[name] !== 'undefined' && Object.prototype.toString.call(this[name]) !== '[object Function]') {
          this[name] = value;
        }
      }
    }

    Stats.prototype._modified = function() {
      this.mtime = new Date;
      this.ctime = new Date;
      return this.emit('modified', this);
    };

    Stats.prototype._modifiedAttributes = function(event) {
      if (event == null) {
        event = 'change';
      }
      this.ctime = new Date;
      return this.emit('modifiedAttributes', this, event);
    };

    Stats.prototype._accessed = function() {
      this.atime = new Date;
      return this.emit('accessed', this);
    };

    Stats.prototype._setAttributes = function(attributes) {
      var name, value;
      if (attributes == null) {
        attributes = {};
      }
      for (name in attributes) {
        value = attributes[name];
        if (Object.prototype.toString.call(this[name]) !== '[object Function]') {
          this[name] = value;
        }
      }
      return this._modifiedAttributes();
    };

    Stats.prototype._clone = function() {
      var name, stats, value;
      stats = new Stats(this._path, {});
      for (name in this) {
        value = this[name];
        if (Object.prototype.toString.call(this[name]) !== '[object Function]') {
          stats[name] = this[name];
        }
      }
      return stats;
    };

    Stats.prototype.isFile = function() {
      return this._isFile;
    };

    Stats.prototype.isDirectory = function() {
      return this._isDirectory;
    };

    Stats.prototype.isBlockDevice = function() {
      return Errors.notImplemented('isBlockDevice');
    };

    Stats.prototype.isCharacterDevice = function() {
      return Errors.notImplemented('isCharacterDevice');
    };

    Stats.prototype.isSymbolicLink = function() {
      return Errors.notImplemented('isSymbolicLink');
    };

    Stats.prototype.isFIFO = function() {
      return Errors.notImplemented('isFIFO');
    };

    Stats.prototype.isSocket = function() {
      return Errors.notImplemented('isSocket');
    };

    return Stats;

  })(EventEmitter);

  module.exports = Stats;

}).call(this);
