// Generated by CoffeeScript 1.6.3
(function() {
  var Stats;

  Stats = (function() {
    Stats.prototype.__path = null;

    Stats.prototype.__isFile = false;

    Stats.prototype.__isDirectory = false;

    Stats.prototype.dev = 0;

    Stats.prototype.ino = 0;

    Stats.prototype.mode = 0;

    Stats.prototype.nlink = 0;

    Stats.prototype.uid = 0;

    Stats.prototype.gid = 0;

    Stats.prototype.rdev = 0;

    Stats.prototype.size = 0;

    Stats.prototype.blksize = 0;

    Stats.prototype.blocks = 1;

    Stats.prototype.atime = null;

    Stats.prototype.mtime = null;

    Stats.prototype.ctime = null;

    function Stats(__path, data) {
      var name, value;
      this.__path = __path;
      if (data == null) {
        data = {};
      }
      this.atime = new Date;
      this.mtime = new Date;
      this.ctime = new Date;
      for (name in data) {
        value = data[name];
        if (typeof this[name] !== 'undefined' && Object.prototype.toString.call(this[name]) !== '[object Function]') {
          this[name] = value;
        }
      }
    }

    Stats.prototype.__notImplemented = function(method) {
      throw new Error("Method '" + method + "' is not implemented.");
    };

    Stats.prototype.__modified = function() {
      this.mtime = new Date;
      return this.ctime = new Date;
    };

    Stats.prototype.__modifiedAttributes = function() {
      return this.ctime = new Date;
    };

    Stats.prototype.__accessed = function() {
      return this.atime = new Date;
    };

    Stats.prototype.isFile = function() {
      return this.__isFile;
    };

    Stats.prototype.isDirectory = function() {
      return this.__isDirectory;
    };

    Stats.prototype.isBlockDevice = function() {
      return this.__notImplemented('isBlockDevice');
    };

    Stats.prototype.isCharacterDevice = function() {
      return this.__notImplemented('isCharacterDevice');
    };

    Stats.prototype.isSymbolicLink = function() {
      return this.__notImplemented('isSymbolicLink');
    };

    Stats.prototype.isFIFO = function() {
      return this.__notImplemented('isFIFO');
    };

    Stats.prototype.isSocket = function() {
      return this.__notImplemented('isSocket');
    };

    return Stats;

  })();

  module.exports = Stats;

}).call(this);
